### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Halnex** [msalom28/Larasocial#1]
Hello,

I first wanna say, this is a great starter app, thank you for creating it.
However, I'm finding it hard to make it work locally.

I'm on http://localhost/social-app/public (no ports)
I have also changed the path of socket.io.js to my local js directory.
I also had to remove `@foreach($randomLogins as $randomLogin)` from `registration/index.blade.php` because it was giving an error, variable not defined.

This is how I installed it:

1. `git clone https://github.com/msalom28/Larasocial/.git projectname`
2. `composer install`
3. `npm install` (had some troubles, had to install each dependency manually)
4. `php artisan migrate`

When I visit http://localhost/social-app/public, I can see the register form but I cannot register, and I get these errors in the console.

> Uncaught ReferenceError: userId is not defined: main.js line 133

> GET http://localhost:3000/socket.io/?EIO=2&transport=polling&t=1430353276968-0 net::ERR_CONNECTION_REFUSED

I have never used socket.io before so I'm not sure about that port 3000.

Is there anything else left to do to have it working locally?

Thanks.

**Comment by msalom28** [comment]
Hey buddy,

I just added the readme file with instructions.

Thanks
