### ISSUE TITLE
Can't register a new user?

### ISSUE THREAD

**Issue by ishgem** [msalom28/Larasocial#12]
hello msalom, 
Love great work. Please keep it up.
here is the issue, when a register a user , firstly it doesn't save to the mysql database so with that i don't think i login in.
Also does it have admin panel?
Thanks in advance!

**Comment by msalom28** [comment]
Can you confirm that you generated your tables correctly?

**Comment by ishgem** [comment]
Thanks for the response.Yes! The tables were correctly. secondly I went to the user table and check the a particular user's password so I could rest the login form. I was abled to login but the order issue is that when i post comment it gives another error too.
problems are:
1. registration form not working
2. Post form too not working.
Thanks once again!

**Comment by msalom28** [comment]
Are your getting any javascript errors? did you check your front end

**Comment by ishgem** [comment]
yes i did...

**Comment by ishgem** [comment]
here is the error for the login  form
"We're sorry! We were unable to sign you in. Please check your credentials and try again."
but the registration form flashes no error at all. Is not saving into the database am sure of that.

Thanks alot.... I really appreciate your effort!

**Comment by yash2code** [comment]
yes this problem exists
