### ISSUE TITLE
database settings

### ISSUE THREAD

**Issue by kpravin543** [msalom28/Larasocial#16]
I have just started laravel, all i know is database settings are in .env file but when i downloaded this there was no such file

please give detailed installation process for noobs like me 

cheers

**Comment by axonamol** [comment]
You need to create .env file and paste the below code
 and run command php artisan key:generate
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=DATABASENAME
DB_USERNAME=USERNAME
DB_PASSWORD=PASSWORD

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=
