### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by Halnex** [msalom28/Larasocial#2]
I'm getting this error on registration form.

However. the new user is being submitted to the database and I am able to login with it.

I have edited php.ini and added this line

> xdebug.max_nesting_level=200

But that didn't help.

Does it have anything to do with php_smtp not being installed on my local machine?

**Comment by Halnex** [comment]
I added this line to top of `config/app.php`

> ini_set('xdebug.max_nesting_level', 200);

Now, it's showing a new error

> FatalErrorException in RegisterUserCommand.php line 79:
> Class 'App\Commands\Auth' not found

**Comment by Halnex** [comment]
Ok, I have figured it out.

On top of adding that line to the top of `config/app.php`
> ini_set('xdebug.max_nesting_level', 200);

You also need to add a backslash '\' to Auth instance in `app/Commands/RegisterUserCommand.php` on line 79 like this
> \Auth::login($user);

**Comment by msalom28** [comment]
You right I found that error. I just changed it.
