### ISSUE TITLE
Logout error: MethodNotAllowedHttpException 

### ISSUE THREAD

**Issue by Halnex** [msalom28/Larasocial#3]
The logout function is not working. Whenever I attempt to log out, I get this error

> MethodNotAllowedHttpException in compiled.php line 7803:

So what I did to fix it was change the logout route from delete to get

from this
> Route::delete('logout', ['as' => 'logout_path', 'uses' => 'SessionController@destroy']);

to this
> Route::get('logout', ['as' => 'logout_path', 'uses' => 'SessionController@destroy']);

Now on logout, I get this response in the browser:
> {"response":"success"}

Which I assume means it's working. Now we just have to redirect to the registration page.

Please let me know if I have missed anything.

**Comment by msalom28** [comment]
I don't think your front end code is working properly... check "/main.js". and make sure you run "gulp" before updating the file for compiling. When you click the class "logout-link" it should trigger a delete request. search "logout-link" in main.js
