### ISSUE TITLE
Can't add status, it says success in the json returned.

### ISSUE THREAD

**Issue by rishirajpurohit** [msalom28/Larasocial#4]
It should how my timeline or dashboard instead, with the status in there.

do you have a stream where you list all statuses ?.

**Comment by rishirajpurohit** [comment]
feeds module, i guess

**Comment by rishirajpurohit** [comment]
can use some documentation too.

I am really not a pro laravel user , so where is the database ?? am i storing in local files ?

**Comment by ken3d06** [comment]
Check your config->database file , the default is sqlite, and the data sits in the storage folder , database.sqlite 
You can change your default to a database you are used to

**Comment by rishirajpurohit** [comment]
When i add status and click publish on larasocial.in i get json returned : 

{"response":"success","userProfileImage":"http:\/\/larasocial.info\/images\/profileimages\/5de69d9b898fcd8f3698a358c97e45548a70d0aa.jpg","userFirstname":"rex","feedBody":"hello\r\n"}

**Comment by rishirajpurohit** [comment]
on larasocial.info

the link returned is larasocial.info/feeds
