### ISSUE TITLE
Not working with mysql. Any help?

### ISSUE THREAD

**Issue by BrokenBat** [msalom28/Larasocial#6]
Hello I'm new with laravel and node.js This code is exactly what I'm looking for. I wanted to migrate the database to mysql. Database and tables are created that's fine but application doesn't work after migration.  I changed the default database and all variables for laravel. I can only think it's a problem with node.js 

Is it possible to use it with mysql database? If yes, how?
Thank you

**Comment by Horus03** [comment]
I have the same problem, @BrokenBat you can fix that problem?

**Comment by BrokenBat** [comment]
Yes i solved it with a lot of trying. The first reason it didnt work is all mysql tables are empty after migration. You need to seed and insert at least one row manually for empty tables. It somehow solved the issue for me. Ps. dont forget to use php artisan serve and node server.js commands before running the website.
