### ISSUE TITLE
Larasocial deployment on the cloud. 

### ISSUE THREAD

**Issue by chegie** [msalom28/Larasocial#8]
Hello,
I just finished finished my Larasocial app. I deployed it on Heroku. I how do i make  node Js work with the laravel app?

Thanks

**Comment by msalom28** [comment]
Hi,

You need to log in to your server and run node server.js .

If you are running apache you should be fine.

And if you are running on nginx there is extra configuration to be added to your fpm file. https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/

**Comment by chegie** [comment]
I tried it,  it deosn't seem to work.
The thing is with Heroku server i have to specify whta kind of app i am launching in the procfile. WHich is "web: vendor/bin/heroku-php-apache2 public/" for now.

When ran  the web: vendor/bin/heroku-php-apache2 public/ on my server in the console mode, it had no effect on my web app online.

I am still stucked

**Comment by msalom28** [comment]
Do you have nodejs installed on your server? are you running linux?

**Comment by chegie** [comment]
no, i ddint. It looks like i can only run one app on a dyno on Heroku, I have the php(laravel) app running there.

**Comment by msalom28** [comment]
I think you will need to set up a worker dyno separately.

**Comment by chegie** [comment]
ok, I will create a node app on another dyno.
